[images]
git-tree-sha1 = "27a4c26bcdd47eb717bee089ec231a899cb8ef69"
lazy = true

    [[images.download]]
    sha256 = "90834d5320612a1e84b4dd5d3809c5a77fb146c371dcd270bdd474395eddf74a"
    url = "https://github.com/JuliaImages/TestImages.jl/releases/download/v1.7.0-artifacts/images.tar.gz"
