[images]
git-tree-sha1 = "e752bdc739f34d02e79c7fa834bc2f2e0d71c7e0"
lazy = true

    [[images.download]]
    sha256 = "e34b7292ed927ec7fe7a6d9f20f2cb29d14d57db1cce5553a1c5c75ce383c38c"
    url = "https://github.com/JuliaImages/TestImages.jl/releases/download/v1.6.1-artifacts/images.tar.gz"

[images_dip3e]
git-tree-sha1 = "9006b49888eceebbde587484f1e5573956f8448b"
lazy = true

    [[images_dip3e.download]]
    sha256 = "1449c5a5b5a4fb30889493ec057fffcb0170ec855a2d01e1a77fdc265db91db1"
    url = "https://github.com/JuliaImages/TestImages.jl/releases/download/v1.7.0-artifacts/images_dip3e.tar.gz"
