[images]
git-tree-sha1 = "0a14c45feb55b96e550ad290aec52f5edb7bfea9"
lazy = true

    [[images.download]]
    sha256 = "e6ce734f75a0a6bc2e908fa93d145ac59380f087cf340fd72f4719550ce87bc7"
    url = "https://github.com/JuliaImages/TestImages.jl/releases/download/v1.6.0-artifacts/images.tar.gz"
