[images]
git-tree-sha1 = "e752bdc739f34d02e79c7fa834bc2f2e0d71c7e0"
lazy = true

    [[images.download]]
    sha256 = "e34b7292ed927ec7fe7a6d9f20f2cb29d14d57db1cce5553a1c5c75ce383c38c"
    url = "https://github.com/JuliaImages/TestImages.jl/releases/download/v1.6.1-artifacts/images.tar.gz"
